### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/tigre#18]
This issue is about remote web drivers to using appium and your support.

TODO:

- [ ] Study exclusive capabilities #19 
- [ ] Create a module to start support #20
  - Create a similar builder like remote web drivers
  - Use de Tigre base class
- [ ] Testing using [selenoid](https://aerokube.com/selenoid/latest/#_android) #issueNumber
- [ ] Testing using [docker-android](https://github.com/budtmo/docker-android) #issueNumber
- [ ] Documentate capabilities, similar #15

**Comment by vmesel** [comment]
Hey @dunossauro how can I get things working locally and what should i do to help have this issue done!

**Comment by dunossauro** [comment]
Selenoid example: https://github.com/aerokube/demo-tests/blob/master/src/test/java/com/aerokube/selenoid/AndroidRemoteApkTest.java
