### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/tigre#23]
The principal objective of this issue is to organize features to Tigre version 1.0

- [ ] Local web driver support #24
  Create a wrapper to use the same API in all contexts, Like remote usage in documentation
- [ ] Remote web driver support
  Create a builder structure for dynamic importing
  - [ ] Default dynamic capabilities #26
  - [ ] Remote browsers #21
  - [ ] Mobile (appium) web driver support #18 
  - [x] Url configuration support
  - [ ] Authentication support #CreateNewIssue
- [ ] Setup and publication on pypi
- [ ] Tigre documentation #16
